server {
    listen       80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /user-api/ {
        # ======================================================================
        # [ 개발 환경 스위칭 설정 ] 두 옵션 중 하나만 주석 해제하여 사용하세요.
        # ======================================================================
        
        # 📌 [방법 A] 로컬 개발 전용 (로컬 도커 API 컨테이너로 연결)
        # -> 로컬에서 백엔드 코드를 직접 수정하며 테스트하고 싶을 때 사용합니다.
        proxy_pass http://api:8080/;

        # 📌 [방법 B] 원격 AWS 및 깃허브 제출용 (원격 AWS 개발 ALB로 연결)
        # -> 로컬 백엔드를 켜지 않거나, 완성본을 깃허브(GitHub)에 올릴 때는 이 주석을 해제해 주세요.
        # proxy_pass https://onde-alb-207957013.ap-northeast-2.elb.amazonaws.com/;
        # proxy_ssl_server_name on;
        # proxy_ssl_name onde.click;
        # proxy_ssl_verify off;
        # proxy_set_header Host onde.click;      
        # # =========================================================================

        # proxy_set_header X-Real-IP $remote_addr;
        # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /admin-api/ {
        # =========================================================================
        # [ 개발 환경 스위칭 설정 ] 두 옵션 중 하나만 주석 해제하여 사용하세요.
        # =========================================================================
        
        # 📌 [방법 A] 로컬 개발 전용 (로컬 도커 ADMIN 컨테이너로 연결)
        # -> 로컬에서 백엔드 코드를 직접 수정하며 테스트하고 싶을 때 사용합니다.
        proxy_pass http://admin:8081/;

        # 📌 [방법 B] 원격 AWS 및 깃허브 제출용 (원격 AWS 개발 ALB로 연결)
        # -> 로컬 백엔드를 켜지 않거나, 완성본을 깃허브(GitHub)에 올릴 때는 이 주석을 해제해 주세요.
        # proxy_pass https://onde-alb-207957013.ap-northeast-2.elb.amazonaws.com/;
        # proxy_ssl_server_name on;
        # proxy_ssl_name onde.click;
        # proxy_ssl_verify off;
        # proxy_set_header Host onde.click;
        # # =========================================================================

        # proxy_set_header X-Real-IP $remote_addr;
        # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # proxy_set_header X-Forwarded-Proto $scheme;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

